WebApplication1/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class Employee
    {
        [Key]
        public int Id { get; set; }


        [Required(ErrorMessage = "Please fill field Name")]
        [RegularExpression(@"^([a-zA-Z])[a-zA-Z_-]*[\w_-]*[\S]$|^([a-zA-Z])[0-9_-]*[\S]$|^[a-zA-Z]*[\S]$", ErrorMessage = "Please enter upper or lower case alphabet only")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Please fill field Surname")]
        [RegularExpression(@"^([a-zA-Z])[a-zA-Z_-]*[\w_-]*[\S]$|^([a-zA-Z])[0-9_-]*[\S]$|^[a-zA-Z]*[\S]$", ErrorMessage = "Please enter upper or lower case alphabet only")]
        public string Surname { get; set; }

        [Required(ErrorMessage = "Please fill field Birth Date")]
        public string BirthDate { get; set; }


        public string Gender { get; set; }

        public int ContactNumber { get; set; }


        [Required(ErrorMessage = "Please fill field Email")]
        [RegularExpression("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9]+)*\\.([a-z]{2,4})$", ErrorMessage = "Invalid email format.")]
        public string Email { get; set; }
    }
}

WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/HRData.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public class HRDataget
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please fill field Social Security Number")]
        public int SocialSecurityNumber { get; set; }


       

        [Required(ErrorMessage = "Please fill field Employee ID")]
        public int EmployeeId { get; set; }




        [Required(ErrorMessage = "Please fill field Salary")]
        public int Salary { get; set; }

    }
}

WebApplication1/Models/TaskContext.cs
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models
{
    public class TaskContext : DbContext
    {
        public DbSet<Employee> employees { get; set; }
        public DbSet<HRDataget> Hrdatas { get; set; }
        public TaskContext(DbContextOptions options) : base(options)
        {

        }
    }
}

WebApplication1/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class EmployeeController : Controller
    {
        public TaskContext context;

        public EmployeeController(TaskContext context)
        {
            this.context = context;
        }

        public IActionResult All()
        {
            ViewBag.employees = context.employees;
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Employee e)
        {
            if (ModelState.IsValid)
            {
                context.employees.Add(e);
                context.SaveChanges();
                return Redirect("/employee/all");
            }

            return View(e);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            if(id == 0)
            {
                return NotFound();
            }

            Employee employee = context.employees.Find(id);

            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        [HttpPost]
        public IActionResult Edit(Employee e)
        {
            if (ModelState.IsValid)
            {
                context.employees.Update(e);
                context.SaveChanges();
                return Redirect("/employee/all");
            }
            return View(e);
        }


        public IActionResult Delete(int id)
        {
            Employee employee = context.employees.FirstOrDefault(e => e.Id == id);

            if(employee != null)
            {
                context.Remove(employee);
                context.SaveChanges();
                return Redirect("/employee/all");
            }
            return View();
        }
    }
}

WebApplication1/Controllers/HRDataController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HRDataController : Controller
    {
        private readonly TaskContext context;
        public HRDataController(TaskContext context)
        {
            this.context = context;
        }

        public IActionResult All()
        {
            ViewBag.hrdata = context.Hrdatas;
            return View();
        }


        [HttpGet]
        public  IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(HRDataget h)
        {
            if (ModelState.IsValid)
            {
                context.Hrdatas.Add(h);
                context.SaveChanges();
                return Redirect("/hrdata/all");
            }

            return View(h);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            HRDataget hrdata = context.Hrdatas.Find(id);

            if (hrdata == null)
            {
                return NotFound();
            }

            return View(hrdata);
        }

        [HttpPost]
        public IActionResult Edit(HRDataget h)
        {
            if (ModelState.IsValid)
            {
                context.Hrdatas.Update(h);
                context.SaveChanges();
                return Redirect("/hrdata/all");
            }

            return View(h);
        }


        public IActionResult Delete(int id)
        {
            HRDataget hrdata = context.Hrdatas.FirstOrDefault(h => h.Id == id);
            if(hrdata != null)
            {
                context.Remove(hrdata);
                context.SaveChanges();
                return Redirect("/HRData/all");
            }
            return View();
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Views/Employee/Add.cshtml
@model Employee
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<h2>Employee Registration</h2>
<form method="post" action="/employee/add">
    <div>
        <label>Name</label>
        <input name="Name" type="text" class="input-group-text">
        <span asp-validation-for="Name" style="color:red"></span>
    </div>    


     <div>
        <label>Surname</label>
        <input name="Surname" type="text" class="input-group-text">
        <span asp-validation-for="Surname" style="color:red"></span>
    </div>  


     <div>
        <label>Birth date</label>
        <input name="BirthDate" type="text" class="input-group-text">
        <span asp-validation-for="BirthDate" style="color:red"></span>
    </div>  


     <div>
        <label>Gender</label>
        <input name="Gender" type="text" class="input-group-text">
        <span asp-validation-for="Gender" style="color:red"></span>
    </div>  


     <div>
        <label>Contact number</label>
        <input name="ContactNumber" type="text" class="input-group-text">
        <span asp-validation-for="ContactNumber" style="color:red"></span>
    </div>  


     <div>
        <label>Email</label>
        <input name="Email" type="text" class="input-group-text">
        <span asp-validation-for="Email" style="color:red"></span>
    </div>  


    <button class="btn btn-outline-success mt-3">Confirm</button>
</form>

WebApplication1/Views/Employee/All.cshtml
@model Employee
@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<div  class=" table-bordered mt-4">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Birth Date</th>
            <th>Gender</th>
            <th>Contact Number</th>
            <th>Email</th>
            <th></th>
        </tr>
    
        @foreach(Employee elm in ViewBag.employees)
        {
            <tr>
                <td>@elm.Id</td>
                <td>@elm.Name</td>
                <td>@elm.Surname</td>
                <td>@elm.BirthDate</td>
                <td>@elm.Gender</td>
                <td>@elm.ContactNumber</td>
                <td>@elm.Email</td>
                <td class="btn btn-info">
                    <a asp-controller="Employee" asp-action="Edit" asp-route-id="@elm.Id">Edit</a>
                </td>
                <td class="btn btn-dark">
                    <a asp-controller="Employee" asp-action="Delete" asp-route-id="@elm.Id">Delete</a>
                </td>
            </tr>
        }
    </table>
</div>

WebApplication1/Views/Employee/Edit.cshtml
@model Employee
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<h2>Employee Registration</h2>
<form method="post" action="/employee/edit">
    <div>
        <label>Name</label>
        <input name="Name" type="text" class="input-group-text">
        <span asp-validation-for="Name" style="color:red"></span>
    </div>    


     <div>
        <label>Surname</label>
        <input name="Surname" type="text" class="input-group-text">
        <span asp-validation-for="Surname" style="color:red"></span>
    </div>  


     <div>
        <label>Birth date</label>
        <input name="BirthDate" type="text" class="input-group-text">
        <span asp-validation-for="BirthDate" style="color:red"></span>
    </div>  


     <div>
        <label>Gender</label>
        <input name="Gender" type="text" class="input-group-text">
        <span asp-validation-for="Gender" style="color:red"></span>
    </div>  


     <div>
        <label>Contact number</label>
        <input name="ContactNumber" type="text" class="input-group-text">
        <span asp-validation-for="ContactNumber" style="color:red"></span>
    </div>  


     <div>
        <label>Email</label>
        <input name="Email" type="text" class="input-group-text">
        <span asp-validation-for="Email" style="color:red"></span>
    </div>  


    <button class="btn btn-outline-success mt-3">Update</button>
</form>

WebApplication1/Views/HRData/Add.cshtml
@model HRDataget
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<form method="post" action="/HRData/add">
    
    <div>
        <label>Social Security Number</label>
        <input type="text" class="input-group-text" name="SocialSecurityNumber">
        <span style="color:red" asp-validation-for="SocialSecurityNumber"></span>
    </div>
    

    <div>
        <label>Employee ID</label>
        <input type="text" class="input-group-text" name="EmployeeId">
        <span style="color:red" asp-validation-for="EmployeeId"></span>
    </div>


    <div>
        <label>Salary</label>
        <input type="text" class="input-group-text" name="Salary">
        <span style="color:red" asp-validation-for="Salary"></span>

    </div>

    <button class="btn btn-outline-success  mt-3">Confirm</button>
</form>

WebApplication1/Views/HRData/All.cshtml
@{
    ViewData["Title"] = "All";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<div style="font-size:25px">Payroll</div>
<div class="table-bordered mt-4">
    <table class="table">
        <tr>
            <th>Social Security Number</th>
            <th>Employee Id</th>
            <th>Salary</th>
            <th></th>
        </tr>
        @foreach(HRDataget elm in ViewBag.hrdata)
        {
            <tr>
                <td>@elm.SocialSecurityNumber</td>
                <td>@elm.EmployeeId</td>
                <td>@elm.Salary</td>
                <td class="btn btn-info">
                    <a  asp-controller="HRData" asp-action="Edit" asp-route-id="@elm.Id">Edit</a>
                </td>
                <td class="btn btn-dark">
                    <a  asp-controller="HRData" asp-action="Delete" asp-route-id="@elm.Id">Delete</a>
                </td>
            </tr>
        }

    </table>
</div>
    
       
    

WebApplication1/Views/HRData/Edit.cshtml
@model HRDataget
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<form method="post" action="/HRData/edit">
    
    <div>
        <label>Social Security Number</label>
        <input type="text" class="input-group-text" name="SocialSecurityNumber">
        <span style="color:red" asp-validation-for="SocialSecurityNumber"></span>
    </div>
    

    <div>
        <label>Employee ID</label>
        <input type="text" class="input-group-text" name="EmployeeId">
        <span style="color:red" asp-validation-for="EmployeeId"></span>
    </div>


    <div>
        <label>Salary</label>
        <input type="text" class="input-group-text" name="Salary">
        <span style="color:red" asp-validation-for="Salary"></span>

    </div>

    <button class="btn btn-outline-success  mt-3">Update</button>
</form>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication1/Views/Layouts/DefaultLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>DefaultLayout</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark">

        <div class="container-fluid">
        <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="/employee/all">Employees</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/employee/add">New Employee</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/hrdata/all">HR Data</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/hrdata/add">New Payroll</a>
                </li>
            </ul>
        </div>

    </nav>



    
    <div class="container">@RenderBody()</div>

</body>
</html>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>